### ISSUE TITLE
[Feature Request] Missing License

### ISSUE THREAD

**Issue by abramhindle** [apple1417/OpenHotfixLoader#1]
Hi Apple1417!

Really neat work!

Can you choose a FLOSS license and apply it to the codebase? It makes it clear to others how they may reuse/use your contributions.

Given how quick people are to close up the contributions of others I do have some suggestions:
* GPL3
* AGPL3

Both of these licenses will ensure that if anyone uses your code, recipients will have to be granted source code too. They will ensure that your code is not used in the commercial cheat market due to licensing.

Alternative suggestions that don't force open sourcing of derivatives include:
* Apache version 2.0
Or give up and just go with BSD 2 clause or MIT license and have people close up your contributions and sell it on ebay :-)

Solution: To achieve this you could download https://www.gnu.org/licenses/gpl-3.0.txt and rename it to LICENSE in the root of this project.

Sincerely,

your pal abram/skruntskrunt

**Comment by abramhindle** [comment]
Oh you'll want to copy to append whatever license you choose to the original licenses of the projects you link to:
https://github.com/TsudaKageyu/minhook/blob/4a455528f61b5a375b1f9d44e7d296d47f18bb18/LICENSE.txt

Maybe just take their LICENSE file verbatim?

**Comment by abramhindle** [comment]
I've added 2 pull requests which achieve either goal: GPL3, or BSD
* https://github.com/apple1417/OpenHotfixLoader/pull/3 [GPL3]
* https://github.com/apple1417/OpenHotfixLoader/pull/2 [BSD]

**Comment by apple1417** [comment]
done in #3
