### ISSUE TITLE
Linux Auto-updating links from Chrome

### ISSUE THREAD

**Issue by pr0nstache** [apple1417/OpenHotfixLoader#11]
Dragging a mod download link from google chrome on Linux, does not produce a mod that loads into the game (to use auto-updating).

example:
original file name `raw.githubusercontent.com-WedMar15202309-29-30GMT-0600(MDT).html`
changed file name `StandAlone Third Person.html`

attached the html file, renmaed as .txt because github doesn't allow uploading .html

[file contents.txt](https://github.com/apple1417/OpenHotfixLoader/files/10981913/file.contents.txt)

expected behavior:
from the instructions in the Read Me: drag the download link into [windows] file explorer to create an auto-updating mod.

If the Chrome/Linux bookmark files are just too different it's not a big deal, just letting you know the behavior.

**Comment by apple1417** [comment]
Yeah not too surprising that a different desktop manager handles it differently.

For url downloads, we just look for a line `URL=<url>` somewhere in your mods folder. Windows shortcuts use this syntax, as do [XDG .desktop entries](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), so for most users it's just automatic (other lines not matching a command are ignored). Your environment has created the "safer", guaranteed to work cross platform, version, a raw html file which instantly redirects when opened in a browser.

I'm not about to bring in a whole html parser just to try catch this edge case, so you'll just have to create a file and add your url commands manually (you can put multiple in a single file). The whole drag a url thing is really just some handwaviness to simply things for the average user.

**Comment by pr0nstache** [comment]
Thanks, that's not a big deal -I figured it was a problem on my end. Just dumping the links in an empty file is way easier than moving bookmark files around and renaming them.
