### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Worlingkit** [apple1417/OpenHotfixLoader#12]
All day I struggle with the "bootloaders".
Open Loader Writes in the log "pluginLoader" what is connected:
Loading Plugin: E:\Borderlands 3 Directors Cut\OakGame\Binaries\Win64\Plugins\OpenHotfixLoader.dll
But there is no OpenHotfixLoader in the game
There is NO comment on this

And B3XM at startup, does not allow you to go through the Start screen (Press the button, nothing happens)
There, for half a year now, everyone has a problem, but there is no author

comments are closed in redux mod

Does anyone know how to run your mod?

**Comment by Worlingkit** [comment]
It seems I understand the problem. I'm running the game in lan mode.
The reason is that now my PC is far from the city, and I have no way to run the game online. How can this be corrected?

**Comment by apple1417** [comment]
It cannot. It's a fundamental assumption of this type of modding - we need to get Gearbox's hotfixes to be able to inject our own.
