### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by KrisVish** [apple1417/OpenHotfixLoader#14]
Hi Apple1417

Please help us to load hotfix mods into borderlands 3 using your openhotfixloader when we do not have internet connection. 

Earlier when we tested, it only worked when there is internet connection and we enter server signon screen

Please help replying to [redacted]
Thank You
Kris

**Comment by apple1417** [comment]
It's not currently possible, and is unlikely to change at any point in the foreseeable future.

Duplicates #13

**Comment by KrisVish** [comment]
Hi  Apple1417

Sorry  I have one last question
is there any mod for bl3 which makes camera follow projectiles from weapon and upon reaching target will return  

can you develop a mod for above  I will be able to pay a reasonable amount since I am an old aged person

Thank You
Kris
