### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by aj34804** [apple1417/OpenHotfixLoader#16]
Primarily play on console but was wanting to try  Redux Wonderlands and am having an issue with the folder location on my Wonderlands the only two folders within are 'Intermediate' and 'Saved' and can not find the 'Oakgame' folder necessary to install mod for Wonderlands. Tried to find solution and could not find anything online. Looked everywhere in files and came up with nothing. I have it on Epic Games with Windows 11 computer any advice is appreciated just really want to try it but can not figure this out. 
![image](https://github.com/apple1417/OpenHotfixLoader/assets/142556450/ca48810b-9238-421d-969d-acd3d2cada38)

**Comment by arogl** [comment]
@aj34804 That is the saves folder, you need to install where TTWL has been installed on your computer.

The location depends on whether you have Steam or Epic as the launcher. @apple1417 provides a very clear video in the readme on the front of this repo.

You cannot install on console.
