### ISSUE TITLE
does the game need to be in [ directx 11 ] in order to make injection [ dx11] works? 

### ISSUE THREAD

**Issue by humanana** [apple1417/OpenHotfixLoader#9]
currently test on dx12 but the community patch and 3rd person not working

the injection can not update on news and it's nor working also same on BLHM
on steam version

**Comment by apple1417** [comment]
This is not an issue with ohl. Join the [modding support discord](https://discord.gg/bXeqV8Ef9R) for an faq and more detailed help.
